import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const isProduction = process.argv[2] === 'production';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/highlight',
		'@lezer/common',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	watch: !isProduction,
	target: 'es2018',
	logLevel: "info",
	sourcemap: isProduction ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
});

if (isProduction) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}

